import {
  Check,
  CheckSquare,
  ChevronDown,
  ChevronRight,
  Circle,
  Folder,
  LogOut,
  Moon,
  Palette,
  Plus,
  Search,
  Settings,
  Sun,
  User,
  MoreHorizontal,
  Calendar,
  X,
  Pencil,
  Trash2,
  Columns3,
  LayoutGrid,
  List,
  Filter,
} from "lucide-react";

export {
  CheckSquare as TasksIcon,
  Folder as ProjectsIcon,
  User as ProfileIcon,
  Settings as SettingsIcon,
  LogOut as LogoutIcon,
  Plus as AddIcon,
  Search as SearchIcon,
  Filter as FilterIcon,
  MoreHorizontal as MoreIcon,
  ChevronDown as ChevronDownIcon,
  ChevronRight as ChevronRightIcon,
  Calendar as CalendarIcon,
  X as CloseIcon,
  Check as CheckIcon,
  Sun as SunIcon,
  Moon as MoonIcon,
  Palette as PaletteIcon,
  Circle as CircleIcon,

  // Task actions
  Pencil as EditIcon,
  Trash2 as DeleteIcon,
  Columns3 as FieldsIcon,
  LayoutGrid as BoardIcon,
  List as ListIcon,
};